apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-backend-deployment
  namespace: "2401193"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-backend
  template:
    metadata:
      labels:
        app: mern-backend
    spec:
      imagePullSecrets:
        - name: nexus-secret
      containers:
        - name: backend
          image: 127.0.0.1:30085/sanika-project/loopin-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URL
              value: "mongodb+srv://sanikasurade1:PAkoQtwxDjvJy8La@cluster0.5eramok.mongodb.net/LOOPIN"
            - name: NODE_ENV
              value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: mern-backend-service
  namespace: "2401193"
spec:
  type: ClusterIP
  selector:
    app: mern-backend
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-frontend-deployment
  namespace: "2401193"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-frontend
  template:
    metadata:
      labels:
        app: mern-frontend
    spec:
      imagePullSecrets:
        - name: nexus-secret
      containers:
        - name: frontend
          image: 127.0.0.1:30085/sanika-project/loopin-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mern-frontend-service
  namespace: "2401193"
spec:
  type: ClusterIP
  selector:
    app: mern-frontend
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mern-ingress
  namespace: "2401193"
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: loopin.imcc-projects.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mern-frontend-service
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: mern-backend-service
                port:
                  number: 5000