
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-backend-deployment
  namespace: "2401193"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-backend
  template:
    metadata:
      labels:
        app: mern-backend
    spec:
      imagePullSecrets:
        - name: nexus-secret
      containers:
        - name: backend
          image: 127.0.0.1:30085/sanika-project/loopin-backend:latest
          ports:
            - containerPort: 5002
          env:
            - name: PORT
              value: "5002"

            - name: NODE_ENV
              value: "production"

            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: MONGODB_URL

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET

            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: CLOUDINARY_CLOUD_NAME

            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: CLOUDINARY_API_KEY

            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: CLOUDINARY_API_SECRET

            - name: EMAIL
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: EMAIL

            - name: EMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: EMAIL_PASS

---
apiVersion: v1
kind: Service
metadata:
  name: mern-backend-service
  namespace: "2401193"
spec:
  type: ClusterIP
  selector:
    app: mern-backend
  ports:
    - port: 5002
      targetPort: 5002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-frontend-deployment
  namespace: "2401193"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-frontend
  template:
    metadata:
      labels:
        app: mern-frontend
    spec:
      imagePullSecrets:
        - name: nexus-secret
      containers:
        - name: frontend
          image: 127.0.0.1:30085/sanika-project/loopin-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mern-frontend-service
  namespace: "2401193"
spec:
  type: ClusterIP
  selector:
    app: mern-frontend
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mern-ingress
  namespace: "2401193"
  annotations:
    kubernetes.io/ingress.class: nginx

    # WebSocket support
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/connection-proxy-header: "keep-alive"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"

spec:
  ingressClassName: nginx
  rules:
    - host: loopin.imcc.com
      http:
        paths:
          # 🔹 BACKEND
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: mern-backend-service
                port:
                  number: 5002

          # 🔹 FRONTEND
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mern-frontend-service
                port:
                  number: 80
